import { JobApplication, WishlistJob, InterviewEvent, TriageEmail } from "@/types/application";

export const INITIAL_MOCK_APPLICATIONS: JobApplication[] = [
  {
    id: "app-1",
    thread_id: "18e47f91a2bc4d11",
    company: "Google",
    role: "Senior Software Engineer - Cloud Platform",
    status: "interview",
    applied_date: new Date(Date.now() - 14 * 86400000).toISOString(),
    latest_update_date: new Date(Date.now() - 2 * 3600000).toISOString(),
    sender: "careers-team@google.com",
    subject: "Google Interview Invitation - Technical Round with Engineering Team",
    summary: "Invited to a 45-minute technical system design & coding interview next week with the Distributed Systems team.",
    history_log: [
      {
        date: new Date(Date.now() - 14 * 86400000).toISOString(),
        status: "applied",
        summary: "Application submitted via Google Careers portal.",
        subject: "Thank you for applying to Google",
        sender: "careers@google.com",
      },
      {
        date: new Date(Date.now() - 7 * 86400000).toISOString(),
        status: "reply",
        summary: "Recruiter screened profile and requested availability for phone screen.",
        subject: "Following up on your Google application",
        sender: "sarah.recruiter@google.com",
      },
      {
        date: new Date(Date.now() - 2 * 3600000).toISOString(),
        status: "interview",
        summary: "Passed initial screening; scheduled Round 2 technical interview.",
        subject: "Google Interview Invitation - Technical Round with Engineering Team",
        sender: "careers-team@google.com",
      },
    ],
  },
  {
    id: "app-2",
    thread_id: "18e47f91a2bc4d22",
    company: "Stripe",
    role: "Full Stack Engineer - Connect",
    status: "offer",
    applied_date: new Date(Date.now() - 25 * 86400000).toISOString(),
    latest_update_date: new Date(Date.now() - 8 * 3600000).toISOString(),
    sender: "talent@stripe.com",
    subject: "Job Offer: Full Stack Engineer at Stripe",
    summary: "Official offer extended! Includes base salary, equity grant, and comprehensive benefits package. Offer letter attached.",
    history_log: [
      {
        date: new Date(Date.now() - 25 * 86400000).toISOString(),
        status: "applied",
        summary: "Applied online for Full Stack Engineer.",
        subject: "We received your application for Full Stack Engineer",
        sender: "jobs@stripe.com",
      },
      {
        date: new Date(Date.now() - 18 * 86400000).toISOString(),
        status: "interview",
        summary: "Completed technical assessment and virtual onsite rounds.",
        subject: "Stripe Onsite Schedule Confirmation",
        sender: "talent@stripe.com",
      },
      {
        date: new Date(Date.now() - 8 * 3600000).toISOString(),
        status: "offer",
        summary: "Offer call completed and formal offer letter sent.",
        subject: "Job Offer: Full Stack Engineer at Stripe",
        sender: "talent@stripe.com",
      },
    ],
  },
  {
    id: "app-3",
    thread_id: "18e47f91a2bc4d33",
    company: "Anthropic",
    role: "AI Application Engineer",
    status: "reply",
    applied_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    latest_update_date: new Date(Date.now() - 1 * 86400000).toISOString(),
    sender: "recruiting@anthropic.com",
    subject: "Next Steps: AI Application Engineer at Anthropic",
    summary: "Recruiter reviewed resume and sent over a quick technical questionnaire regarding LLM orchestration and eval frameworks.",
    history_log: [
      {
        date: new Date(Date.now() - 5 * 86400000).toISOString(),
        status: "applied",
        summary: "Submitted application via Greenhouse.",
        subject: "Application received - AI Application Engineer",
        sender: "no-reply@greenhouse.io",
      },
      {
        date: new Date(Date.now() - 1 * 86400000).toISOString(),
        status: "reply",
        summary: "Recruiter follow-up with technical questionnaire.",
        subject: "Next Steps: AI Application Engineer at Anthropic",
        sender: "recruiting@anthropic.com",
      },
    ],
  },
  {
    id: "app-4",
    thread_id: "18e47f91a2bc4d44",
    company: "Airbnb",
    role: "Frontend Engineer - Host Platform",
    status: "applied",
    applied_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    latest_update_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    sender: "automated@airbnb.com",
    subject: "Thank you for applying to Airbnb",
    summary: "Application received and currently under review by hiring team.",
    history_log: [
      {
        date: new Date(Date.now() - 3 * 86400000).toISOString(),
        status: "applied",
        summary: "Application submitted.",
        subject: "Thank you for applying to Airbnb",
        sender: "automated@airbnb.com",
      },
    ],
  },
  {
    id: "app-5",
    thread_id: "18e47f91a2bc4d55",
    company: "Datadog",
    role: "Backend Engineer - Observability",
    status: "rejected",
    applied_date: new Date(Date.now() - 30 * 86400000).toISOString(),
    latest_update_date: new Date(Date.now() - 10 * 86400000).toISOString(),
    sender: "jobs-noreply@datadoghq.com",
    subject: "Update regarding your application at Datadog",
    summary: "Position filled by an internal candidate; profile kept on file for future opportunities.",
    history_log: [
      {
        date: new Date(Date.now() - 30 * 86400000).toISOString(),
        status: "applied",
        summary: "Application submitted.",
        subject: "Datadog Application Received",
        sender: "jobs-noreply@datadoghq.com",
      },
      {
        date: new Date(Date.now() - 10 * 86400000).toISOString(),
        status: "rejected",
        summary: "Application not moving forward.",
        subject: "Update regarding your application at Datadog",
        sender: "jobs-noreply@datadoghq.com",
      },
    ],
  },
];

export const INITIAL_WISHLIST_JOBS: WishlistJob[] = [
  {
    id: "wish-1",
    company: "OpenAI",
    role: "Full Stack Engineer - Systems",
    location: "San Francisco, CA (Hybrid)",
    salary_range: "$220,000 - $310,000",
    url: "https://openai.com/careers/full-stack-engineer",
    notes: "Requires deep experience with Next.js, WebSockets, and real-time streaming interfaces.",
    date_added: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "wish-2",
    company: "Figma",
    role: "Frontend Engineer - Canvas & Collaboration",
    location: "Remote (US)",
    salary_range: "$190,000 - $260,000",
    url: "https://figma.com/careers",
    notes: "Heavy WebGL / WebAssembly & real-time collaborative state synchronization.",
    date_added: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "wish-3",
    company: "Vercel",
    role: "Product Engineer - AI SDK & DX",
    location: "Remote (Global)",
    salary_range: "$180,000 - $240,000",
    url: "https://vercel.com/careers",
    notes: "Passionate about AI interfaces, RSC, Next.js App Router, and DX benchmarking.",
    date_added: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "wish-4",
    company: "Linear",
    role: "Core Application Engineer",
    location: "Remote (EU/US)",
    salary_range: "$190,000 - $250,000",
    url: "https://linear.app/careers",
    notes: "Focus on keyboard shortcuts, offline-first sync engine, and 60fps UX.",
    date_added: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
];

export const INITIAL_INTERVIEW_EVENTS: InterviewEvent[] = [
  {
    id: "int-1",
    application_id: "app-1",
    company: "Google",
    role: "Senior Software Engineer",
    round: "System Design",
    date: new Date(Date.now() + 2 * 86400000).toISOString().split("T")[0],
    time: "14:00",
    duration: "45m",
    interviewer: "David K. (Staff SWE)",
    meeting_url: "https://meet.google.com/abc-defg-hij",
    notes: "Review distributed consensus algorithms (Raft), sharding, and high-throughput write caches.",
  },
  {
    id: "int-2",
    application_id: "app-3",
    company: "Anthropic",
    role: "AI Application Engineer",
    round: "Technical Phone",
    date: new Date(Date.now() + 4 * 86400000).toISOString().split("T")[0],
    time: "11:30",
    duration: "60m",
    interviewer: "Elena R. (Research Engineering Manager)",
    meeting_url: "https://zoom.us/j/1234567890",
    notes: "Discuss LLM streaming architecture, latency optimization, and automated eval suites.",
  },
  {
    id: "int-3",
    application_id: "app-2",
    company: "Stripe",
    role: "Full Stack Engineer",
    round: "Executive Round",
    date: new Date(Date.now() - 1 * 86400000).toISOString().split("T")[0],
    time: "16:00",
    duration: "30m",
    interviewer: "VP of Engineering",
    meeting_url: "https://meet.stripe.com/room-402",
    notes: "Culture alignment and final offer package debrief.",
  },
];

export const INITIAL_TRIAGE_EMAILS: TriageEmail[] = [
  {
    id: "triage-1",
    thread_id: "19a84b01e234",
    company: "Microsoft",
    role: "Software Engineer II - Azure AI",
    sender: "recruiting@microsoft.com",
    subject: "Invitation to Azure AI Technical Screen",
    date: new Date(Date.now() - 1 * 3600000).toISOString(),
    detected_status: "interview",
    confidence_score: 0.98,
    ai_rationale: "Email body explicitly contains 'inviting you to schedule a 45-minute technical screen with our engineering team'.",
    summary: "Invited to schedule a 45-minute technical interview for Azure AI platform team.",
    is_approved: false,
  },
  {
    id: "triage-2",
    thread_id: "19a84b01e567",
    company: "Shopify",
    role: "Senior Frontend Developer",
    sender: "careers@shopify.com",
    subject: "Thank you for applying to Shopify",
    date: new Date(Date.now() - 5 * 3600000).toISOString(),
    detected_status: "applied",
    confidence_score: 0.99,
    ai_rationale: "Standard ATS receipt acknowledgment from Greenhouse/Shopify with confirmation number.",
    summary: "Application confirmation received for Senior Frontend Developer position.",
    is_approved: false,
  },
  {
    id: "triage-3",
    thread_id: "19a84b01e890",
    company: "Meta",
    role: "Product Software Engineer",
    sender: "noreply@meta.careers.com",
    subject: "Update on your application with Meta",
    date: new Date(Date.now() - 12 * 3600000).toISOString(),
    detected_status: "reply",
    confidence_score: 0.92,
    ai_rationale: "Recruiter inquiry asking for updated location preferences and work authorization status.",
    summary: "Recruiter asking to verify work authorization and preferred team focus areas.",
    is_approved: false,
  },
];


